<?php
require_once('vendor/autoload.php');

use JWT;

/*
 * Simple sanitization
 */
$username = filter_input(INPUT_POST, 'username', FILTER_SANITIZE_STRING);
$password = filter_input(INPUT_POST, 'password', FILTER_SANITIZE_STRING);

if ($username && $password) {
    try {
        /*
         * Connect to database to validate credentials
         */
        $db = new PDO('mysql:host=127.0.0.1;dbname=c9', 'tecnom1k3', '');
        
        /*
         * We will fetch user id and password fields for the given username
         */
        $sql = <<<EOL
        select id, password from users where username = ?
EOL;

        $stmt = $db->prepare($sql);
        $stmt->execute(array($username));
        $rs = $stmt->fetch();
        
        if ($rs) {
            /**
             * Password was generated by password_hash(), so we need to use
             * password_verify() to check it.
             * 
             * @see http://php.net/manual/en/ref.password.php
             */
            if (password_verify($password, $rs['password'])) {
                
                /*
                 * Create the token as an array
                 */
                $data = [
                    'id'  => $rs['id'], //userid from the users table
                    'iat' => time(),    //Issued at: time when the token was generated
                    'jti' => uniqid(),  //Json Token Id: an unique identifier for the token
                ];
                
                /**
                 * Encode the array to a JWT string.
                 * Second parameter is the key to encode the token, keep it secure.
                 * You'll need the exact key to verify the token later.
                 * 
                 * The output string can be validated at http://jwt.io/
                 */
                echo JWT::encode($data, '89sdf98sd7a98f7a98sd');
                
            }
        } 
    } catch (Exception $e) {
        echo $e;
    }
}